#!/usr/bin/env python3
"""Compile a full player-age dataset for every squad.

Every player in data/teams/*.json already carries an `age` field (the source of
truth, harvested from Transfermarkt as of the tournament's first day, 2026-06-11).
This script gathers all 48 squads into one consolidated view and writes:

  docs/player-ages.csv  -- machine-readable dataset, one row per player
  docs/player-ages.md   -- browsable dataset: full rosters plus age aggregates
                           (squad averages, the oldest and youngest players,
                           and the overall age distribution)

It is a generated VIEW over the team files -- edit the per-player `age` in
data/teams/<slug>.json, never these outputs, then re-run this script.

Usage: python3 scripts/generate_player_ages.py
"""

import csv
import os
import statistics

from common import (
    DOCS_DIR,
    POSITION_ORDER,
    POSITIONS,
    load_all_teams,
)

# Ages in the team files are stated "as of" the tournament's first matchday,
# matching the convention used by FIFA's and Transfermarkt's published squads.
AGE_AS_OF = "2026-06-11"

CSV_COLUMNS = [
    "team", "group", "team_slug", "player", "position", "club",
    "club_country", "age",
]


def collect_rows(teams):
    """Flatten every squad into one list of per-player dicts."""
    rows = []
    for t in teams:
        for p in t.get("squad", []):
            rows.append({
                "team": t["name"],
                "group": t.get("group", ""),
                "team_slug": t["slug"],
                "player": p.get("name", ""),
                "position": p.get("position", ""),
                "club": p.get("club", ""),
                "club_country": p.get("club_country", ""),
                "age": p.get("age"),
            })
    return rows


def write_csv(rows, path):
    with open(path, "w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=CSV_COLUMNS)
        writer.writeheader()
        for r in rows:
            writer.writerow(r)


def squad_sort_key(player):
    """Order a squad by position (GK, DF, MF, FW) then oldest first."""
    return (POSITION_ORDER.get(player["position"], 9), -(player["age"] or 0))


def write_markdown(teams, rows, path):
    ages = [r["age"] for r in rows if r["age"] is not None]
    n_players = len(rows)
    n_aged = len(ages)

    lines = ["# Player Ages — full dataset", ""]
    lines.append(
        f"_Every player across all {len(teams)} squads "
        f"({n_players} players). Ages are stated as of {AGE_AS_OF}, the "
        "tournament's first matchday — the same convention FIFA and "
        "Transfermarkt use for the published squads. Source of truth: the "
        "`age` field in `data/teams/<slug>.json`; this page and "
        "`player-ages.csv` are generated by `scripts/generate_player_ages.py`._"
    )
    lines.append("")

    # --- summary ---
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Players: **{n_players}** (with a recorded age: **{n_aged}**)")
    if ages:
        lines.append(f"- Average age: **{statistics.mean(ages):.1f}**")
        lines.append(f"- Median age: **{int(statistics.median(ages))}**")
        lines.append(f"- Range: **{min(ages)}–{max(ages)}**")
    lines.append("")

    # --- age distribution ---
    if ages:
        buckets = [
            ("Under 20", lambda a: a < 20),
            ("20–24", lambda a: 20 <= a <= 24),
            ("25–29", lambda a: 25 <= a <= 29),
            ("30–34", lambda a: 30 <= a <= 34),
            ("35 and over", lambda a: a >= 35),
        ]
        lines.append("## Age distribution")
        lines.append("")
        lines.append("| Band | Players | Share |")
        lines.append("|------|---------|-------|")
        for label, pred in buckets:
            count = sum(1 for a in ages if pred(a))
            share = 100 * count / n_aged if n_aged else 0
            lines.append(f"| {label} | {count} | {share:.1f}% |")
        lines.append("")

    # --- oldest / youngest ---
    aged_rows = [r for r in rows if r["age"] is not None]
    oldest = sorted(aged_rows, key=lambda r: (-r["age"], r["player"]))[:15]
    youngest = sorted(aged_rows, key=lambda r: (r["age"], r["player"]))[:15]

    def leaderboard(title, ranked):
        lines.append(f"## {title}")
        lines.append("")
        lines.append("| Rank | Age | Player | Team | Position | Club |")
        lines.append("|------|-----|--------|------|----------|------|")
        for i, r in enumerate(ranked, 1):
            lines.append(
                f"| {i} | {r['age']} | {r['player']} | {r['team']} | "
                f"{r['position']} | {r['club']} |"
            )
        lines.append("")

    leaderboard("15 oldest players", oldest)
    leaderboard("15 youngest players", youngest)

    # --- squads by average age ---
    team_avg = []
    for t in teams:
        sq_ages = [p.get("age") for p in t.get("squad", []) if p.get("age") is not None]
        if sq_ages:
            team_avg.append((t, statistics.mean(sq_ages)))
    team_avg.sort(key=lambda x: x[1], reverse=True)
    lines.append("## Squads by average age")
    lines.append("")
    lines.append("| Rank | Team | Group | Avg age | Youngest | Oldest |")
    lines.append("|------|------|-------|---------|----------|--------|")
    for i, (t, avg) in enumerate(team_avg, 1):
        sq_ages = [p["age"] for p in t["squad"] if p.get("age") is not None]
        lines.append(
            f"| {i} | {t['name']} | {t.get('group','')} | {avg:.1f} | "
            f"{min(sq_ages)} | {max(sq_ages)} |"
        )
    lines.append("")

    # --- full rosters ---
    lines.append("## Full rosters")
    lines.append("")
    for t in teams:
        squad = [
            {**p, "age": p.get("age"), "position": p.get("position", "")}
            for p in t.get("squad", [])
        ]
        squad.sort(key=squad_sort_key)
        sq_ages = [p["age"] for p in squad if p.get("age") is not None]
        avg = f"{statistics.mean(sq_ages):.1f}" if sq_ages else "—"
        lines.append(f"### {t['name']} (Group {t.get('group','?')}) — avg {avg}")
        lines.append("")
        lines.append("| Age | Player | Position | Club |")
        lines.append("|-----|--------|----------|------|")
        for p in squad:
            age = p["age"] if p.get("age") is not None else "—"
            lines.append(
                f"| {age} | {p.get('name','')} | {p.get('position','')} | "
                f"{p.get('club','')} |"
            )
        lines.append("")

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def main():
    teams = load_all_teams()
    if not teams:
        print("No team data found; skipping player-ages dataset.")
        return

    rows = collect_rows(teams)
    os.makedirs(DOCS_DIR, exist_ok=True)
    csv_path = os.path.join(DOCS_DIR, "player-ages.csv")
    md_path = os.path.join(DOCS_DIR, "player-ages.md")
    write_csv(rows, csv_path)
    write_markdown(teams, rows, md_path)

    aged = sum(1 for r in rows if r["age"] is not None)
    print(f"Wrote docs/player-ages.csv and docs/player-ages.md "
          f"({len(rows)} players, {aged} with an age).")

    # Sanity: POSITIONS is referenced for ordering; surface any unknown codes.
    unknown = sorted({r["position"] for r in rows
                      if r["position"] and r["position"] not in POSITIONS})
    if unknown:
        print(f"  note: unrecognised position codes present: {unknown}")


if __name__ == "__main__":
    main()
